site_name: OlivierFest-Agda
site_url: https://pdmosses.github.io/olivierfest-agda/
repo_name: pdmosses/olivierfest-agda
repo_url: https://github.com/pdmosses/olivierfest-agda

use_directory_urls: true

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

  features:
    - content.code.copy
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/Agda-material.css
  - stylesheets/Agda-md.css
  - stylesheets/Agda-md-dark.css
# KaTeX:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
# KaTeX:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

plugins:
- search
- awesome-nav