nav:
  - README.md
  - Notation: md/Notation/index.md
  - ScmQE:
    - md/ScmQE/All/index.md
    - md/ScmQE/
  - Library:
    - md/Library/index.md
    - md/*
  - HTML: html/ScmQE.All.html
  - PDF: pdf/ScmQE.All.pdf

preserve_directory_names: true

sort:
  sections: mixed