nav:
  - index.md
  - Notation: md/Notation/index.md
  - ScmQE:
    - md/ScmQE/index/index.md
    - md/ScmQE/All/index.md
    - md/ScmQE/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/ScmQE.All.html
  - PDF: pdf/ScmQE.All.pdf

# ignore: md/index/index.md

preserve_directory_names: true

sort:
  sections: mixed