nav:
  - index.md
  - md/Notation/index.md
  - ScmQE:
    - md/ScmQE/
  - Library:
    - md/*
  - HTML: html/ScmQE.All.html
  - PDF: pdf/ScmQE.pdf

preserve_directory_names: true

sort:
  sections: mixed